# Uses: https://github.com/marketplace/actions/markdownlint-cli
#
# Be sure to also create a file named "markdownlintconfig.json" with the following contents: 
# {
#     "MD013": false
# }

name: markdownlint check

on: 
  push:
    paths: 
      - '**.md'
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  markdownlint:
    name: call-markdownlint-workflow
    uses: Andy4495/.github/.github/workflows/markdownlint.yml@main         
    with:
      message: ${{ inputs.message }}