# Adapted from: https://github.com/marketplace/actions/compile-arduino-sketches
#
name: Arduino Compile Sketches

on: 
  workflow_call:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string
      fqbn:
        required: true
        type: string
      platform-name:
        required: true
        type: string
      platform-sourceurl:
        required: true
        type: string
      platform-version:
        required: true
        type: string
      libraries:
        required: true
        type: string
      copyfile:
        required: false
        type: string

jobs:
  compile-sketches: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update PATH if using nektos/act locally
        if: ${{ env.ACT }}
        run: |
          echo "/root/.local/bin" >> $GITHUB_PATH
      - name: Copy file if necessary
        if: ${{ inputs.copyfile }}
        run: |
          cp ${{ inputs.copyfile }}-template.h ${{ inputs.copyfile }}.h
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ inputs.fqbn }}
          platforms: |
            - name: ${{ inputs.platform-name }}
              version: ${{ inputs.platform-version }}
              source-url: ${{ inputs.platform-sourceurl }}
          sketch-paths: |
            - .
          verbose: true
          enable-warnings-report: true
          libraries: ${{ inputs.libraries }}
      - name: Print the job summary
        if: ${{ inputs.message }}
        run: |
          echo ${{ inputs.message }} >$GITHUB_STEP_SUMMARY

